language: csharp

sudo: false  # use the new container-based Travis infrastructure

services:
  - mysql

before_script:
  - mysql -e "CREATE USER 'nunit'@'localhost' IDENTIFIED BY 'jkYjgeriE8EIEIPrJNb8';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON rosterstore_nunit.* TO 'nunit'@'localhost';" -uroot

script: 
  - ./build.sh All

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f2c1a02c04d215bdbdbf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
