services:
  - mysql
  - mssql2014

environment:
  connection_mssql: Data Source=(LocalDb)\SQL2014;Database=master;Password=Password12!
  connection_mysql: Server=localhost;Database=rosterstore_nunit;Uid=root;Pwd=Password12!

init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
