// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Yaaf.Xmpp.IM.SQL")]
[assembly: AssemblyProductAttribute("Yaaf.Xmpp.IM.SQL")]
[assembly: AssemblyCopyrightAttribute("Yaaf.Xmpp.IM.SQL Copyright © Matthias Dittrich 2015")]
[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyFileVersionAttribute("0.0.2")]
[assembly: AssemblyInformationalVersionAttribute("0.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.2";
    }
}
